# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1.xci
# IP: The module: 'design_1_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1.xci
# IP: The module: 'design_1_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/xiaobei/Vivado_design/10.15/NVDLA_SMALL/NVDLA_3.srcs/sources_1/bd/design_1/ip/design_1_ila_0_1/design_1_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
