set_property SEVERITY {Warning} [get_drc_checks NSTD-1]

set_property SEVERITY {Warning} [get_drc_checks RTSTAT-1]

set_property SEVERITY {Warning} [get_drc_checks UCIO-1]

set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[0].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[1].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[2].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[3].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[4].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[5].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[6].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[7].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[8].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[9].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[10].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[11].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[12].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[13].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[14].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[15].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[16].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[17].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[18].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[19].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[20].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[21].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[22].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[23].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[24].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[25].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[26].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[27].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[28].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[29].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[30].RO_i/osc_1/osc_out]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE [get_nets design_1_i/ring_osc_top_2_0/inst/ROs[31].RO_i/osc_1/osc_out]